
name: Build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

      - name: Checkout doc-base
        uses: actions/checkout@v7
        with:
          repository: php/doc-base
          path: doc-base

      - name: Checkout doc-en
        uses: actions/checkout@v7
        with:
          repository: php/doc-en
          path: en

        # GH actions/checkout automatically merges, but tends to get stuck in the past.
        # See: https://github.com/php/doc-base/pull/329

      - name: Checkout and merge doc-pt_br
        uses: actions/checkout@v7
        with:
          path: pt_br

      - name: Build manual.xml
        run: |
          php doc-base/configure.php --disable-libxml-check --enable-xml-details --redirect-stderr-to-stdout --with-lang=pt_br 2>&1
          sha1sum doc-base/temp/manual.xml




        # Merge PR brahcn into default branch using *current* branch heads:
        # - github.event.pull_request.base.ref : main/master
        # - github.event.pull_request.head.sha : PR head
        #
        # Does not work:
        # - actions/checkout without fetch-depth / fetch-tags
        # - git fetch by github.event.pull_request.head.ref
        # - git merge --squash --no-commit fails with no ident
        #
        # TODO:
        # - In case of conflict, GH's 'Squash and merge' uses
        #   --strategy-option=theirs or ours? Probably theirs
        #   in this case, as we position into master ("here")
        #   and pulls from feature ("there").




      - name: Alternative 1, uses plain git commands
        run:  rm -rf pt_br

      - name: Checkout and merge doc-pt_br (plain git)
        run: |
          # Plain git merge
          git --version

          path=pt_br
          repo=${{ github.event.pull_request.base.repo.clone_url }}
          hash=${{ github.event.pull_request.head.sha }}

          git clone -q --single-branch $repo $path
          cd $path

          git fetch -q --no-tags --prune --no-recurse-submodules origin $hash
          echo
          git remote -v
          echo
          git show-ref -d --head
          echo

          git config user.name  "nobody"
          git config user.email "nobody@example.com"

          git merge -m "Merge" $hash

      - name: Build manual.xml, again
        run: |
          php doc-base/configure.php --disable-libxml-check --enable-xml-details --redirect-stderr-to-stdout --with-lang=pt_br 2>&1
          sha1sum doc-base/temp/manual.xml



      - name: Alternative 2, uses actions/checkout@v7 + userland merge
        run:  rm -rf pt_br

      - name: Checkout and merge doc-pt_br (actions/checkout+userland)
        uses: actions/checkout@v7
        with:
          fetch-depth: 0
          fetch-tags: true
          path: pt_br
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Squash merge doc-pt_br
        run: |
          # Squash merge

          cd pt_br
          git show-ref -d --head
          echo

          # Give the PR detached head a name, to avoid warnings
          git branch head-${{ github.event.pull_request.head.sha }}

          # Checkout default branch by name, to always get the current head
          git checkout ${{ github.event.pull_request.base.ref }}
          echo

          # Squash changes from the PR branch into here (default branch)
          # TODO: missing a --strategy-option=theirs on merge --squash ?
          git -c user.name="none" -c user.email="none@example.com" merge -q --squash ${{ github.event.pull_request.head.sha }}
          git -c user.name="none" -c user.email="none@example.com" commit -m "Squash merge"
          echo

          git status --short
          git diff --stat
          echo

      - name: Build manual.xml, again
        run: |
          php doc-base/configure.php --disable-libxml-check --enable-xml-details --redirect-stderr-to-stdout --with-lang=pt_br 2>&1
          sha1sum doc-base/temp/manual.xml
