
name: Build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

      - name: Checkout doc-base
        uses: actions/checkout@v7
        with:
          repository: php/doc-base
          path: doc-base

      - name: Checkout doc-en
        uses: actions/checkout@v7
        with:
          repository: php/doc-en
          path: en

        # GH actions/checkout automatically merges, but tends to get stuck in the past.
        # See: https://github.com/php/doc-base/pull/329

      - name: Checkout doc-pt_br (actions/checkout)
        uses: actions/checkout@v7
        with:
          path: pt_br

      - name: Build manual.xml
        run: |
          php doc-base/configure.php --disable-libxml-check --enable-xml-details --redirect-stderr-to-stdout --with-lang=pt_br 2>&1
          sha1sum doc-base/temp/manual.xml

      - name: Alternative
        run:  rm -rf pt_br

        # Clone default branch and merge PR using only plain git:
        # - clone --single-branch selects the default branch;
        # - github.event.pull_request.head.sha maps to PR tip, unmerged.

      - name: Checkout doc-pt_br (plain git)
        run: |
          # Plain git merge

          path=pt_br

          set -x
          git --version
          git clone -q --single-branch ${{ github.event.pull_request.base.repo.clone_url }} "$path"
          cd "$path"
          git config user.name  "nobody"
          git config user.email "nobody@example.com"
          git fetch -q --no-tags --prune --no-recurse-submodules origin ${{ github.event.pull_request.head.sha }}
          git merge -q -m "Merge" ${{ github.event.pull_request.head.sha }}

      - name: Build manual.xml, again
        run: |
          php doc-base/configure.php --disable-libxml-check --enable-xml-details --redirect-stderr-to-stdout --with-lang=pt_br 2>&1
          sha1sum doc-base/temp/manual.xml
