
name: Build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

      - name: Checkout doc-base
        uses: actions/checkout@v7
        with:
          repository: php/doc-base
          path: doc-base

      - name: Checkout doc-en
        uses: actions/checkout@v7
        with:
          repository: php/doc-en
          path: en

        # GH actions/checkout, automatically merges, but tends to get stuck in the past.
        # See: https://github.com/php/doc-base/pull/329

      - name: Checkout doc-pt_br (automatic merge)
        uses: actions/checkout@v7
        with:
          path: pt_br

      - name: Build manual.xml
        run: |
          php doc-base/configure.php --disable-libxml-check --enable-xml-details --redirect-stderr-to-stdout --with-lang=pt_br 2>&1
          sha1sum doc-base/temp/manual.xml



      - name: Alternative path, uses userland merge instead
        run:  rm -rf pt_br

      - name: Checkout doc-pt_br (no merge)
        uses: actions/checkout@v7
        with:
          fetch-depth: 0
          fetch-tags: true
          path: pt_br
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Userland merge
        run: |
          # Merge into main/master from current, known names/SHAS.
          #
          # - github.event.pull_request.base.ref : main/master
          # - github.event.pull_request.head.sha : PR head
          #
          # Does not work:
          # - actions/checkout without fetch-depth / fetch-tags
          # - git fetch by github.event.pull_request.head.ref
          echo

          cd pt_br

          # Fetch history of two points, for merge tree walking (necessary?)
          # git fetch -q origin ${{ github.event.pull_request.base.ref }}
          # git fetch -q origin ${{ github.event.pull_request.head.sha }}
          git show-ref -d --head
          echo

          # Give the detached head a name, to avoid warnings
          git switch -c commit-${{ github.event.pull_request.head.sha }}
          echo

          # Checkout main/master, by name, to reach it's last commit
          git checkout ${{ github.event.pull_request.base.ref }}
          echo

          # Squash and merge, from the branch SHA
          git merge --squash ${{ github.event.pull_request.head.sha }}
          echo

          git status --short
          git diff --stat
          echo

      - name: Build manual.xml, again
        run: |
          php doc-base/configure.php --disable-libxml-check --enable-xml-details --redirect-stderr-to-stdout --with-lang=pt_br 2>&1
          sha1sum doc-base/temp/manual.xml
